[make][pre-commit]Check CRD schema to avoid update issues
openstack-k8s-operators/manila-operator pull request #366
Opened 2024-11-27 14:32 UTC by mrkisaolamb

The new crd-schema-check make target compares the CRD schema of the patch with the schema on the tip of main and report errors on non backward compatible changes.

This make target now also run in pre-commit both locally and in CI.

This make target uses https://github.com/openshift/crd-schema-checker to do the actual checking.

Related: OSPRH-11833

2024-11-27 14:48 UTC, fmount approved these changes
/lgtm

2024-11-28 08:31 UTC, gibizer requested changes

2024-11-28 08:31 UTC, gibizer commented on Makefile
> +	INSTALL_DIR=$(LOCALBIN) BASE_REF="$${PULL_BASE_SHA:-$(BRANCH)}" hack/crd-schema-checker.sh
Need to define BRANCH in the makefile

2024-11-28 09:03 UTC, mrkisaolamb commented on Makefile
> +	INSTALL_DIR=$(LOCALBIN) BASE_REF="$${PULL_BASE_SHA:-$(BRANCH)}" hack/crd-schema-checker.sh
done

2024-11-28 10:26 UTC, stuggi commented
/retest

2024-11-28 14:23 UTC, stuggi approved these changes
/lgtm

2024-11-28 14:27 UTC, merged