Add updated Manila KUTTL tests
openstack-k8s-operators/manila-operator pull request #98
Opened 2023-07-07 16:25 UTC by vhariria

2023-07-13 23:44 UTC, gouthampacha commented
/ok-to-test

2023-07-18 11:31 UTC, fmount commented
@vhariria @gouthampacha added [1] so we'll be able to trigger the job here when we're ready.

[1] https://github.com/openshift/release/pull/41363

2023-07-26 03:17 UTC, gouthampacha requested changes
Hi Vida, 

many things to fix up here.. i took a shot and got things working on your test host, could you please look at https://github.com/openstack-k8s-operators/manila-operator/pull/109 and adapt it? Or we can work on that PR instead.. another thing to note is to avoid merge commits... they mess up the diff

2023-07-26 19:01 UTC, gouthampacha requested changes
Thanks for the changes; some more pointers inline. I will close https://github.com/openstack-k8s-operators/manila-operator/pull/109/files now since you've ported the suggestions over..

2023-07-26 19:01 UTC, gouthampacha commented on kuttl-test.yaml
> +   - events                     # Remove spammy event logs
not spammy at all :)
just that we don't intend on doing string matches with the event log..

2023-07-26 20:35 UTC, vhariria commented on config/samples/manila_v1beta1_manila.yaml
> +    [ DEFAULT ]
This change reverts the sample file to original file in the repo

2023-07-26 20:39 UTC, vhariria commented on config/samples/manila_v1beta1_manila.yaml
> +  manilaAPI: {}
These changes revert the file back to original repo version

2023-07-27 04:43 UTC, gouthampacha commented
/retest-required

2023-07-27 14:47 UTC, gouthampacha commented
/retest

2023-07-27 15:58 UTC, gouthampacha commented
/lgtm 

Thanks for pushing this @vhariria

2023-07-27 15:58 UTC, gouthampacha approved these changes

2023-07-27 16:20 UTC, merged